version: "3"

services:

  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile_pgsql
    environment:
      - "POSTGRES_PASSWORD=openbamz"
    volumes:
      - dev-openbamz-db:/var/lib/postgresql/data
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U postgres -d postgres"
      timeout: 2s
  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "NODE_ENV=development"
      - "JWT_SECRET=dev_jwt_token"
      - "DB_HOST=db"
      - "DB_USER=postgres"
      - "DB_PASSWORD=openbamz"
      - "DB_PORT=5432"
      - "DB_NAME=_openbamz"
      - "DATA_DIR=/home/node/data"
    volumes:
      - dev-openbamz-data:/home/node/data
    depends_on:
      - db
    depends_on: 
      db: 
        condition: service_healthy

volumes:
  dev-openbamz-db:
    external: true
  dev-openbamz-data:
    external: true
